services:
  postgres:
    image: docker.io/library/postgres:17
    container_name: postgres_service
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Redis Cache Service
  redis:
    image: docker.io/library/redis:latest
    container_name: redis_service
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # RabbitMQ Message Broker
  rabbitmq:
    image: docker.io/library/rabbitmq:3-management
    container_name: rabbitmq_service
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  # MailHog SMTP service for email testing
  mailhog:
    image: docker.io/mailhog/mailhog:latest
    container_name: mailhog_service
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_network

  # N8N Workflow
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - TZ=Asia/Kolkata
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  n8n_data:
    driver: local

networks:
  app_network:
    driver: bridge